"use client";
import { motion } from 'framer-motion';
import { CheckCircle2, Plus, X, Flag } from 'lucide-react';
import { Button } from '../../common';

interface AIGeneratedTask {
  title?: string;
  description?: string;
  priority?: string;
  dueDate?: string;
  completed?: boolean;
}

interface AIConfirmationModalProps {
  isOpen: boolean;
  aiGeneratedTask: AIGeneratedTask | null;
  onClose: () => void;
  onConfirm: () => void;
  getPriorityColor: (priority: string) => string;
}

export default function AIConfirmationModal({
  isOpen,
  aiGeneratedTask,
  onClose,
  onConfirm,
  getPriorityColor
}: AIConfirmationModalProps) {
  if (!isOpen || !aiGeneratedTask) return null;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-slate-800/90 backdrop-blur-md border border-slate-600/50 rounded-xl p-4 sm:p-6 w-full max-w-lg mx-4"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-500/20 rounded-lg">
              <CheckCircle2 className="w-5 h-5 text-green-400" />
            </div>
            <h3 className="text-lg font-semibold text-white">AI Generated Task</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="bg-slate-700/30 rounded-lg p-4 mb-6">
          <h4 className="text-white font-medium mb-2">{aiGeneratedTask.title}</h4>
          {aiGeneratedTask.description && aiGeneratedTask.description.trim() && (
            <p className="text-slate-300 text-sm mb-3">{aiGeneratedTask.description}</p>
          )}
          <div className="flex items-center gap-4 text-sm">
            <div className={`px-2 py-1 rounded-full text-xs font-medium border ${getPriorityColor(aiGeneratedTask.priority || 'medium')}`}>
              <Flag className="w-3 h-3 inline mr-1" />
              {aiGeneratedTask.priority || 'medium'} priority
            </div>
          </div>
        </div>

        <p className="text-slate-400 text-sm mb-6">
          This task was generated by AI based on your description. You can add it to your task list or make changes later.
        </p>

        <div className="flex flex-col sm:flex-row justify-end gap-3">
          <Button
            onClick={onClose}
            variant="secondary"
            className="px-4 py-2 w-full sm:w-auto"
          >
            Cancel
          </Button>
          <Button
            onClick={onConfirm}
            className="bg-green-500 hover:bg-green-600 text-white px-6 py-2 w-full sm:w-auto"
          >
            <div className="flex items-center gap-2">
              <Plus className="w-4 h-4" />
              Add Task
            </div>
          </Button>
        </div>
      </motion.div>
    </motion.div>
  );
}